# Default configuration for the Minecraft plugin

plugin:
  enable-command: true # Whether to enable the /wiki <id> command
  command:
    name: wiki # The name of the command to use
    aliases: # Aliases for the command
      - w
      - wiki-entry
    permission: wiki.use # Permission required to use the command, can be empty
    description: Get a wiki entry by ID # Description of the command
    usage: /wiki <id> # Usage message for the command
  api:
    base-url: https://api.example.com/wiki # Base URL for the wiki API
    timeout: 5000 # Timeout for API requests in milliseconds