name: PR Build Check

on:
  pull_request:
    branches: [ main, master, dev ]

jobs:
  build-backend:
    name: Build Backend (Spring Boot)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

  build-plugin:
    name: Build Minecraft Plugin
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./minecraft-plugin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build plugin with Gradle
        run: ./gradlew build
